=== joellord/cli-slides/assets/json-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "title": {
        "type": "string"
      },
      "presenter": {
        "type": "string"
      },
      "date": {
        "type": "string"
      },
      "conference": {
        "type": "string"
      },
      "location": {
        "type": "string"
      },
      "company": {
        "type": "string"
      },
      "twitter": {
        "type": "object",
        "properties": {
          "presenter": {
            "type": "string"
          },
          "event": {
            "type": "string"
          }
        },
        "additionalProperties": true,
        "required": [
          "presenter",
          "event"
        ]
      },
      "frame": {
        "type": "object",
        "properties": {
          "top": {
            "type": "object",
            "properties": {
              "center": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "center"
            ]
          },
          "bottom": {
            "type": "object",
            "properties": {
              "left": {
                "type": "array",
                "items": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  }
                ],
                "additionalItems": true
              },
              "center": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "left",
              "center"
            ]
          }
        },
        "additionalProperties": true,
        "required": [
          "top",
          "bottom"
        ]
      },
      "slides": {
        "type": "array",
        "items": [
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "text": {
                "type": "string"
              },
              "code": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "title",
              "text",
              "code"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "multistep": {
                "type": "boolean"
              },
              "multistepType": {
                "type": "string"
              },
              "text": {
                "type": "string"
              },
              "code": {
                "type": "string"
              },
              "notes": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "title",
              "multistep",
              "multistepType",
              "text",
              "code",
              "notes"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "multistep": {
                "type": "boolean"
              },
              "multistepType": {
                "type": "string"
              },
              "text": {
                "type": "string"
              },
              "code": {
                "type": "array",
                "items": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  }
                ],
                "additionalItems": true
              },
              "notes": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "title",
              "multistep",
              "multistepType",
              "text",
              "code",
              "notes"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "diagram": {
                "type": "array",
                "items": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  }
                ],
                "additionalItems": true
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "title",
              "diagram"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "list": {
                "type": "array",
                "items": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  },
                  {
                    "type": "string"
                  }
                ],
                "additionalItems": true
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "title",
              "list"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "character": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "character",
              "text"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "character": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "character",
              "text"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "character": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "character",
              "text"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "character": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "character",
              "text"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "character": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "character",
              "text"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "title",
              "text"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "left": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "list": {
                    "type": "array",
                    "items": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "string"
                      },
                      {
                        "type": "string"
                      }
                    ],
                    "additionalItems": true
                  }
                },
                "additionalProperties": true,
                "required": [
                  "title",
                  "list"
                ]
              },
              "right": {
                "type": "object",
                "properties": {
                  "text": {
                    "type": "array",
                    "items": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "string"
                      },
                      {
                        "type": "string"
                      },
                      {
                        "type": "string"
                      }
                    ],
                    "additionalItems": true
                  }
                },
                "additionalProperties": true,
                "required": [
                  "text"
                ]
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "left",
              "right"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "title",
              "text"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "title": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "title"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "title": {
                "type": "string"
              }
            },
            "additionalProperties": true,
            "required": [
              "type",
              "title"
            ]
          }
        ],
        "additionalItems": true
      }
    },
    "additionalProperties": true,
    "required": [
      "title",
      "presenter",
      "date",
      "conference",
      "location",
      "company",
      "twitter",
      "frame",
      "slides"
    ]
  }

=== joellord/cli-slides/demo.json
{
  "$schema": "./assets/json-schema.json",
  "title": "My New Talk",
  "presenter": "Joel Lord",
  "date": "November 25, 2019",
  "conference": "This Event",
  "location": "Toronto, Canada",
  "company": "Red Hat OpenShift",
  "twitter": {
    "presenter": "@joel__lord",
    "event": "#EventHashtag"
  },
  "frame": {
    "top": {
      "center": "title"
    },
    "bottom": {
      "left": ["twitter.presenter", "twitter.event"],
      "center": "company"
    }
  },
  "slides": [
    {
      "type": "code",
      "title": "Slide Title",
      "text": "Description for this code sample",
      "code": "[green]npm install[reset] [reverse]-g[reset] [cyan]cli-slides[reset]"
    },
    {
      "type": "code",
      "title": "Slide Title",
      "multistep": true,
      "multistepType": "highlight",
      "text": "Highlighted snippets displayed one at a time",
      "code": "[reverse]npm install[reset] [reverse]-g[reset] [reverse]cli-slides[reset]",
      "notes": "You can also add footer notes"
    },
    {
      "type": "code",
      "title": "Slide Title",
      "multistep": true,
      "multistepType": "line",
      "text": "Description for this code sample",
      "code": [
        "[green]$[reset] npm -v",
        "[green]$[reset] npm install cli-slides",
        "[green]$[reset] npx cli-slides ./demo.json"
      ],
      "notes": "You can also add footer notes"
    },
    {
      "type": "diagram",
      "title": "Slide Title",
      "diagram": [
        "-----------------------------",
        "|            Box A          |",
        "-----------------------------",
        "               |             ",
        "               v             ",
        "-----------------------------",
        "|            Box B          |",
        "-----------------------------"  ]
    },
    {
      "type": "list",
      "title": "Title of the slide",
      "list": [
        "Item number 1",
        "Item number 2",
        "Item number 3"
      ]
    },
    {
      "type": "speaking",
      "character": "over-cubbie",
      "text": "Hey there! I'm over-cubbie"
    },
    {
      "type": "speaking",
      "character": "me",
      "text": "And I'm... 'me'"
    },
    {
      "type": "speaking",
      "character": "me-oh-no",
      "text": "Oh noes!"
    },
    {
      "type": "speaking",
      "character": "silly-face",
      "text": "What's going on?"
    },
    {
      "type": "speaking",
      "character": "scream",
      "text": "OMG"
    },
    {
      "type": "simple",
      "title": "Slide Title",
      "text": "You can use a long string here, text will wrap. \n\nOr use \\n for multiple lines"
    },
    {
      "type": "split",
      "left": {
        "title": "Left Side Title",
        "list": [
          "Item 1",
          "Item 2",
          "Item 3"
        ]
      },
      "right": {
        "text": [
          "You can put some text here",
          "or maybe a diagram",
          "",
          "Sky's the limit"
        ]
      }
    },
    {
      "type": "terminal",
      "title": "Terminal Inside The Terminal",
      "text": "You can run some shell commands here. Try 'ls'."
    },
    {
      "type": "title",
      "title": "CLI Slides"
    },
    {
      "type": "titleOnly",
      "title": "New Section"
    }
  ]
}
